IIRC/IIRC/urls.py
from django.conf import settings

from django.conf.urls import url, include
from django.contrib import admin
from blogs import views
from arabicblog import views as ar_views
from filebrowser.sites import site

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r"^blog/", include("pinax.blog.urls", namespace="pinax_blog")),
    url(r"^ar/blog/", include("arabicblog.urls", namespace="arabicblog")),
    url(r"^ajax/images/", include("pinax.images.urls", namespace="pinax_images")),
    url(r'^tinymce/', include('tinymce.urls')),

    url(r'^$', views.homepage, name='homepage'),
    url(r'^lar/', views.arHome, name='arHome'),

    url(r'^en/', views.en, name='en'),
    url(r'^ar/', ar_views.ar, name='ar'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^about/', views.about, name='about'),

    url(r'^blogs/', include('blogs.urls')),
    url(r'^base/', views.index, name='index'),
    url(r'^test/', views.post, name='test'),
    url(r'^home/', views.home, name='home'),

    # url(r"^account/", include("account.urls")),
    # url(r"^comments/", include("pinax.comments.urls", namespace="pinax_comments")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

IIRC/arabicblog/urls.py
from django.conf.urls import url

from .conf import settings
from .views import (
    BlogIndexView,
    DateBasedPostDetailView,
    SecretKeyPostDetailView,
    SectionIndexView,
    StaffPostDetailView,
)

app_name = "arabicblog"

urlpatterns = [
    url(r"^$", BlogIndexView.as_view(), name="blog"),
    url(r"^section/(?P<section>[-\w]+)/$", SectionIndexView.as_view(), name="blog_section"),
    url(r"^post/(?P<post_pk>\d+)/$", StaffPostDetailView.as_view(), name="blog_post_pk"),
    url(r"^post/(?P<post_secret_key>\w+)/$", SecretKeyPostDetailView.as_view(), name="blog_post_secret"),
    url(r"^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$", DateBasedPostDetailView.as_view(), name="blog_post"),
]

IIRC/arabicblog/forms.py
from django import forms
from django.utils import timezone
from django.utils.functional import curry
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _

from pinax.images.models import ImageSet

from .models import Post, Section

from tinymce.widgets import TinyMCE


FIELDS = [
    "section",
    "kateb",
    "title",
    "slug",
    "teaser",
    "content",
    "video",
    "description",
]


class PostFormMixin(object):

    def __init__(self, *args, **kwargs):
        super(PostFormMixin, self).__init__(*args, **kwargs)
        post = self.instance

    def save_post(self, post):
        post.updated = timezone.now()
        post.save()

        return post


class AdminPostForm(PostFormMixin, forms.ModelForm):

    title = forms.CharField(
        label=_("Title"),
        max_length=90,
        widget=forms.TextInput(attrs={"style": "width: 50%;"}),
    )
    slug = forms.CharField(
        label=_("Slug"),
        widget=forms.TextInput(attrs={"style": "width: 50%;"})
    )
    teaser = forms.CharField(
        label=_("Teaser"),
        widget=forms.Textarea(attrs={"style": "width: 80%;"}),
    )
    content = forms.CharField(
        widget=TinyMCE(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        ))
    video = forms.CharField(
        label=_("Video"),
        widget=forms.Textarea(attrs={"style": "width: 80%;"}),
        required=False
    )
    description = forms.CharField(
        label=_("Description"),
        widget=forms.Textarea(attrs={"style": "width: 80%;"}),
        required=False
    )

    class Meta:
        model = Post
        fields = '__all__'
        # fields = FIELDS

    def save(self, blog=None):
        post = super(AdminPostForm, self).save(commit=False)
        if blog:
            post.blog = blog
        return self.save_post(post)


class PostForm(PostFormMixin, forms.ModelForm):

    teaser = forms.CharField(widget=forms.Textarea())
    content = forms.CharField(
        widget=TinyMCE(
            attrs={'required': False, 'cols': 30, 'rows': 10}))
    class Meta:
        model = Post
        fields = [
            "section",
            "title",
            "teaser",
            "content",
            "video",
            "description",

        ]

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        if Section.objects.count() < 2:
            self.section = Section.objects.first()
            del self.fields["section"]
        else:
            self.section = None

    def save(self, blog=None, kateb=None):
        post = super(PostForm, self).save(commit=False)
        if blog:
            post.blog = blog
        if kateb:
            post.author = kateb
        if self.section:
            post.section = self.section
        post.slug = slugify(post.title)
        return self.save_post(post)

IIRC/arabicblog/templates/snippet/arHome.html
{%load static%}

<!DOCTYPE html>
<html>

<head>
    <link rel="shortcut icon" href="{% static 'img/544x180-300x99-387x128-67.png' %}" type="image/x-icon">
    {% block meta %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    {% endblock %}
    {% block css %}
    {% include 'snippet/bootstrap3css.html' %}
    {% include 'snippet/mobicss.html' %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" language="javascript">
         $(document).ready(function() {
            $("#driver").click(function(event){
               $('#stage').load('/');
            });
         });


    </script>
    {% endblock %}
    {% block extracss %}{% endblock %}
    {% block extra_head %}{% endblock %}

</head>

<body>
{% block navbar %}
<div id="stage" style="background-color:cc0;">
    <section id="menu-0">

        <nav class="navbar navbar-dropdown bg-color transparent navbar-fixed-top">
            <div class="container">

                <div class="mbr-table">
                    <div class="mbr-table-cell">
                        <div class="navbar-brand">
                            <a href="../" class="navbar-logo">
                                <img src="{% static 'img/544x180-300x99-387x128-67.png' %}" alt="IIRC"></a>
                            <a class="navbar-caption" href="../">مركز الدكتور اقبال للبحوث والدراسات</a>
                        </div>
                    </div>
                    <div class="mbr-table-cell">

                        <button class="navbar-toggler pull-xs-right hidden-md-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                            <div class="hamburger-icon"></div>
                        </button>

                        <ul class="nav-dropdown collapse pull-xs-right nav navbar-nav navbar-toggleable-sm"
                            id="exCollapsingNavbar">
                            <li class="nav-item"><a class="nav-link link" href="/contact/">تواصل معنا</a></li>
                            <li class="nav-item"><a class="nav-link link" href="/about/">حول الموقع</a></li>
                            <li class="nav-item"><a class="nav-link link" href="/ar/">الرئيسية</a></li>
                            <li class="nav-item">
                                <input class="btn btn-primary" type="button" id="driver" value="English"/>
                            </li>
                        </ul>
                        <button hidden="" class="navbar-toggler navbar-close" type="button" data-toggle="collapse"
                                data-target="#exCollapsingNavbar">
                            <div class="close-icon"></div>
                        </button>

                    </div>
                </div>

            </div>
        </nav>
    </section>


    {% endblock %}
    {% block body %}
    {% block content %}

    <section class="mbr-section mbr-section-hero mbr-section-full mbr-parallax-background mbr-section-with-arrow"
             id="header1-0" style="background-image: url({% static 'img/header1.png' %});">
        <div class="mbr-overlay" style="opacity: 0.4; background-color: rgb(0, 0, 0);"></div>
        <div class="mbr-table-cell">
            <div class="container">
                <div class="row">
                    <div class="mbr-section col-md-10 col-md-offset-1 text-xs-center">
                        <h1 class="mbr-section-title display-1">مرحبا بكم في مركز الدكتور اقبال للدراسات والابحاث</h1>
                        <p class="mbr-section-lead lead">

                            ر مركز اقبال للدراسات والابحاث مركز اقبال للابحاث مركز اقبال
                            <br>
                            تتوفر المقالات والاخبار باللغتین
                        </p>
                        <div class="mbr-section-btn">
                            <a class="btn btn-lg btn-info" href="../ar">عربي</a>
                            <a class="btn btn-lg btn-white" href="../en">انكليزي</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mbr-arrow mbr-arrow-floating" aria-hidden="true">
            <a href="#social-buttons2-0">
                <i class="mbr-arrow-icon"></i>
            </a>
        </div>
    </section>
    {% include 'snippet/follow-us_ar.html' %}

    {% endblock %}
    {% block extracontent %}{% endblock %}

    {% block sidebar %}{% endblock %}
    {% block extrasidebar %}{% endblock %}

    {% endblock %}
    {% block extraBodyBeforeFooter %}{% endblock %}

    {% block footer %}
    {% include 'snippet/mainFooter_ar.html' %}
    {% endblock %}
    <footer class="mbr-small-footer mbr-section mbr-section-nopadding" id="footer1-0"
            style="background-color: rgb(50, 50, 50); padding-top: 1.75rem; padding-bottom: 1.75rem;">
        <div class="container">
            <p class="text-xs-center">Copyright (c) 2019 IIRC.</p>
        </div>
    </footer>
</div>
{% block js %}
{% include 'snippet/mainjs.html' %}

<input name="animation" type="hidden">
{% endblock %}
{% block extrajs %}{% endblock %}
</body>

</html>

IIRC/arabicblog/templates/snippet/bootstrap4css_rtl.html
{%load static%}
<link rel="stylesheet" href="{% static 'css-rtl/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css-rtl/carousel.rtl.css' %}">
<link rel="stylesheet" href="{% static 'css-rtl/Article-List.css' %}">
<link rel="stylesheet" href="{% static 'css-rtl/navbar-top-fixed.rtl.css' %}">
<link rel="stylesheet" href="{% static 'css-rtl/sticky-footer.rtl.css' %}">

IIRC/arabicblog/templates/snippet/follow-us_ar.html
{%load static%}

<section class="mbr-section mbr-section-md-padding mbr-parallax-background" id="social-buttons2-0"
         style="background-image: url({% static 'img/social.jpg' %}); padding-top: 90px; padding-bottom: 90px;">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-xs-center">
                <h3 class="mbr-section-title display-2">تابعونا</h3>
                <div>
                    <a class="btn btn-social" title="Twitter" target="_blank" href="https://twitter.com/">
                        <i class="socicon socicon-twitter"></i>
                    </a>
                    <a class="btn btn-social" title="Facebook" target="_blank" href="https://www.facebook.com/">
                        <i class="socicon socicon-facebook"></i>
                    </a>
                    <a class="btn btn-social" title="YouTube" target="_blank" href="https://www.youtube.com/">
                        <i class="socicon socicon-youtube"></i>
                    </a> <a class="btn btn-social" title="Instagram" target="_blank"
                            href="https://instagram.com">
                    <i class="socicon socicon-instagram"></i>
                </a>
                </div>
            </div>
        </div>
    </div>
</section>

IIRC/arabicblog/templates/snippet/mainFooter_ar.html
<section class="rtl mbr-footer footer4 mbr-section mbr-section-md-padding" id="contacts4-0" style="background-color: rgb(46, 46, 46); padding-top: 90px; padding-bottom: 90px;">

    <div class="container-fluid" align="right">
        <div class="mbr-contacts row">
            <div class="col-sm-8">
                <div class="row">
                    <div class="col-sm-6">
                        <p><strong>العنوان</strong><br>
                            كلية الهندسة - برديس فارابي - جامعة طهران<br>
                            قم - ايران<br><br><br>
                            <strong>التواصل</strong><br>
                            Email: shah_hasan.reza@ut.ac.ir<br>
                            Phone: +98 910 093 4016<br>
                        </p>
                    </div>
                    <div class="col-sm-6"><p class="mbr-contacts__text"><strong>صفحات التواصل الاجتماعي</strong></p><ul class="mbr-contacts__list"><li><a href="https://facebook.com/">فيسبوك</a></li><li><a href="https://twitter.com/">تويتر</a><a class="text-white" href=""></a></li><li><a href="https://Instagram.com">انستاغرام</a><a class="text-white" href=""></a></li></ul></div>
                </div>
            </div>
           <div class="col-sm-4">
                <p><strong>شركاؤنا</strong>
                    <br>
                        <a href="http://iircenter.net/"> Iqbal information and research center</a>
                    <br><br>
                        <a href="http://www.mwmpak.org/"> Majlis Wahdat Muslimin Pakistan</a>
                </p>
                <!--<form action="https://mobirise.com/" method="post">-->


                    <!--<div class="form-group">-->
                        <!--<label class="form-control-label" for="contacts4-0-email">Email<span class="form-asterisk">*</span></label>-->
                        <!--<input type="email" class="form-control input-sm input-inverse" name="email" required="" data-form-field="Email" id="contacts4-0-email">-->
                    <!--</div>-->

                    <!--<div class="form-group">-->
                        <!--<label class="form-control-label" for="contacts4-0-message">Message</label>-->
                        <!--<textarea class="form-control input-sm input-inverse" name="message" data-form-field="Message" rows="4" id="contacts4-0-message"></textarea>-->
                    <!--</div>-->
                    <!--<div class="mbr-buttons mbr-buttons&#45;&#45;right btn-inverse"><button type="submit" class="btn btn-sm btn-black">Contact us</button></div>-->
                <!--</form>-->
            </div>
        </div>
    </div>
</section>

IIRC/arabicblog/templates/snippet/navbar2_ar.html
{%load static%}
{% load arabicblog_tags %}

<nav class="rtl navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">
        <img src="{% static 'img/544x180-300x99-387x128-67.png' %}" width="80" height="35" alt="IIRC">
      </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav rtl" style="margin-left: auto!important;">
      <li class="nav-item active">
        <a class="nav-link" href="/ar/">الرئيسية <span class="sr-only">(current)</span></a>
      </li>
            </li>
            {% blog_sections as sections %}
            {% for section in sections %}
            {% url "arabicblog:blog_section" section.slug as section_url %}
            <li class="nav-item">
                <a style="text-transform: capitalize;" class="nav-link" href="{{ section_url }}">{{ section.name }}</a>
            </li>
            {% endfor %}

        </ul>
        <form action="/en/" class="form-inline mt-2 mt-md-0">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">English</button>
        </form>
    </div>
</nav>

IIRC/arabicblog/templates/snippet/navbar2withsearch_ar.html
{%load static%}
{% load arabicblog_tags %}

<nav class="rtl navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">
        <img src="{% static 'img/544x180-300x99-387x128-67.png' %}" width="80" height="35" alt="IIRC">
      </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav rtl" style="margin-left: auto!important;">
      <li class="nav-item active">
        <a class="nav-link" href="/ar/">الرئيسية <span class="sr-only">(current)</span></a>
      </li>
            </li>
            {% blog_sections as sections %}
            {% for section in sections %}
            {% url "arabicblog:blog_section" section.slug as section_url %}
            <li class="nav-item">
                <a style="text-transform: capitalize;" class="nav-link" href="{{ section_url }}">{{ section.name }}</a>
            </li>
            {% endfor %}
        </ul>
        {% if current_section == "all" %}
            {% url "arabicblog:blog" as search_url %}
        {% else %}
            {% url "arabicblog:blog_section" current_section.slug as search_url %}
        {% endif %}
        <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" aria-label="Search" type="search" placeholder="ابحث عن..." name="q"
                   value="{{ search_term|default:"" }}">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">بحث</button>
        </form>
    </div>
</nav>