IIRC/IIRC/urls.py
from django.conf import settings

from django.conf.urls import url, include
from django.contrib import admin
from blogs import views
from arabicblog import views as ar_views
from filebrowser.sites import site

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r"^blog/", include("pinax.blog.urls", namespace="pinax_blog")),
    url(r"^ar/blog/", include("arabicblog.urls", namespace="arabicblog")),
    url(r"^ajax/images/", include("pinax.images.urls", namespace="pinax_images")),
    url(r'^tinymce/', include('tinymce.urls')),

    url(r'^$', views.homepage, name='homepage'),
    url(r'^lar/', views.arHome, name='arHome'),

    url(r'^en/', views.en, name='en'),
    url(r'^ar/', ar_views.ar, name='ar'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^about/', views.about, name='about'),

    url(r'^blogs/', include('blogs.urls')),
    url(r'^base/', views.index, name='index'),
    url(r'^test/', views.post, name='test'),
    url(r'^home/', views.home, name='home'),

    # url(r"^account/", include("account.urls")),
    # url(r"^comments/", include("pinax.comments.urls", namespace="pinax_comments")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

IIRC/arabicblog/urls.py
from django.conf.urls import url

from .conf import settings
from .views import (
    BlogIndexView,
    DateBasedPostDetailView,
    SecretKeyPostDetailView,
    SectionIndexView,
    StaffPostDetailView,
)

app_name = "arabicblog"

urlpatterns = [
    url(r"^$", BlogIndexView.as_view(), name="blog"),
    url(r"^section/(?P<section>[-\w]+)/$", SectionIndexView.as_view(), name="blog_section"),
    url(r"^post/(?P<post_pk>\d+)/$", StaffPostDetailView.as_view(), name="blog_post_pk"),
    url(r"^post/(?P<post_secret_key>\w+)/$", SecretKeyPostDetailView.as_view(), name="blog_post_secret"),
    url(r"^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$", DateBasedPostDetailView.as_view(), name="blog_post"),
]

IIRC/templates/snippet/asdada.html
x

<section class="mbr-footer footer4 mbr-section mbr-section-md-padding" id="contacts4-0" style="background-color: rgb(46, 46, 46); padding-top: 90px; padding-bottom: 90px;">

    <div class="container-fluid">
        <div class="mbr-contacts row">
            <div class="col-sm-8">
                <div class="row">
                    <div class="col-sm-6">
                        <p><strong>Address</strong><br>
                            College of Farabi, Faculity of Engineering<br>
                            Qom, Iran<br><br><br>
                            <strong>Contacts</strong><br>
                            Email: shah_hasan.reza@ut.ac.ir<br>
                            Phone: +98 910 093 4016<br>
                        </p>
                    </div>
                    <div class="col-sm-6"><p class="mbr-contacts__text"><strong>Links</strong></p><ul class="mbr-contacts__list"><li><a href="https://facebook.com/">Facebook</a></li><li><a href="https://twitter.com/">Twitter</a><a class="text-white" href="https://mobirise.com/mobirise-free-win.zip"></a></li><li><a href="https://Instagram.com">Instagram</a><a class="text-white" href="https://mobirise.com/mobirise-free-mac.zip"></a></li></ul></div>
                </div>
            </div>
            <div class="col-sm-4">

                <form action="https://mobirise.com/" method="post">


                    <div class="form-group">
                        <label class="form-control-label" for="contacts4-0-email">Email<span class="form-asterisk">*</span></label>
                        <input type="email" class="form-control input-sm input-inverse" name="email" required="" data-form-field="Email" id="contacts4-0-email">
                    </div>

                    <div class="form-group">
                        <label class="form-control-label" for="contacts4-0-message">Message</label>
                        <textarea class="form-control input-sm input-inverse" name="message" data-form-field="Message" rows="4" id="contacts4-0-message"></textarea>
                    </div>
                    <div class="mbr-buttons mbr-buttons--right btn-inverse"><button type="submit" class="btn btn-sm btn-black">Contact us</button></div>
                </form>
            </div>
        </div>
    </div>
</section>

IIRC/templates/snippet/bootstrap3css.html
{%load static%}
<link rel="stylesheet" href="{% static 'css/mobiCSS/bootstrap.min.css' %}">

IIRC/templates/snippet/bootstrap4css.html
{%load static%}
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/fonts/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'css/Article-List.css' %}">
<link rel="stylesheet" href="{% static 'css/navbar-top-fixed.css' %}">
<link rel="stylesheet" href="{% static 'css/blog.css' %}">

<style>
        .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        }

        @media (min-width: 768px) {
        .bd-placeholder-img-lg {
        font-size: 3.5rem;
        }
        }
        body {
        padding-top: 100px;
        }
</style>

IIRC/templates/snippet/bootstrap4js.html
{% load static %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

IIRC/templates/snippet/follow-us.html
{%load static%}

<section class="mbr-section mbr-section-md-padding mbr-parallax-background" id="social-buttons2-0"
         style="background-image: url({% static 'img/social.jpg' %}); padding-top: 90px; padding-bottom: 90px;">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-xs-center">
                <h3 class="mbr-section-title display-2">FOLLOW US</h3>
                <div>
                    <a class="btn btn-social" title="Twitter" target="_blank" href="https://twitter.com/">
                        <i class="socicon socicon-twitter"></i>
                    </a>
                    <a class="btn btn-social" title="Facebook" target="_blank" href="https://www.facebook.com/">
                        <i class="socicon socicon-facebook"></i>
                    </a>
                    <a class="btn btn-social" title="YouTube" target="_blank" href="https://www.youtube.com/">
                        <i class="socicon socicon-youtube"></i>
                    </a> <a class="btn btn-social" title="Instagram" target="_blank"
                            href="https://instagram.com">
                    <i class="socicon socicon-instagram"></i>
                </a>
                </div>
            </div>
        </div>
    </div>
</section>

IIRC/templates/snippet/imagegallary.html
            <div class="row">
                {% for post in articles %}
                <div class="col-6 pb-2 mg-1	">
                    <div class="card bg-dark text-white">
                        <img class="card-img img-fluid" src="{{post.image.url}}" style="width:450px;height:255px;" >
                        <div class="card-img-overlay d-flex">
                            <a href="{{post.get_absolute_url}}" class="align-self-end">
                                <h6 class="card-title">{{post.title}}</h6>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}

IIRC/templates/snippet/mainFooter.html
<section class="mbr-footer footer4 mbr-section mbr-section-md-padding" id="contacts4-0" style="background-color: rgb(46, 46, 46); padding-top: 90px; padding-bottom: 90px;">

    <div class="container-fluid">
        <div class="mbr-contacts row">
            <div class="col-sm-8">
                <div class="row">
                    <div class="col-sm-6">
                        <p><strong>Address</strong><br>
                            College of Farabi, Faculity of Engineering<br>
                            Qom, Iran<br><br><br>
                            <strong>Contacts</strong><br>
                            Email: shah_hasan.reza@ut.ac.ir<br>
                            Phone: +98 910 093 4016<br>
                        </p>
                    </div>
                    <div class="col-sm-6"><p class="mbr-contacts__text"><strong>Links</strong></p><ul class="mbr-contacts__list"><li><a href="https://facebook.com/">Facebook</a></li><li><a href="https://twitter.com/">Twitter</a><a class="text-white" href="https://mobirise.com/mobirise-free-win.zip"></a></li><li><a href="https://Instagram.com">Instagram</a><a class="text-white" href="https://mobirise.com/mobirise-free-mac.zip"></a></li></ul></div>
                </div>
            </div>
           <div class="col-sm-4">
                <p><strong>Our Partners</strong>
                    <br>
                        <a href="http://iircenter.net/"> Iqbal information and research center</a>
                    <br><br>
                        <a href="http://www.mwmpak.org/"> Majlis Wahdat Muslimin Pakistan</a>
                </p>
                <!--<form action="https://mobirise.com/" method="post">-->


                    <!--<div class="form-group">-->
                        <!--<label class="form-control-label" for="contacts4-0-email">Email<span class="form-asterisk">*</span></label>-->
                        <!--<input type="email" class="form-control input-sm input-inverse" name="email" required="" data-form-field="Email" id="contacts4-0-email">-->
                    <!--</div>-->

                    <!--<div class="form-group">-->
                        <!--<label class="form-control-label" for="contacts4-0-message">Message</label>-->
                        <!--<textarea class="form-control input-sm input-inverse" name="message" data-form-field="Message" rows="4" id="contacts4-0-message"></textarea>-->
                    <!--</div>-->
                    <!--<div class="mbr-buttons mbr-buttons&#45;&#45;right btn-inverse"><button type="submit" class="btn btn-sm btn-black">Contact us</button></div>-->
                <!--</form>-->
            </div>
        </div>
    </div>
</section>

IIRC/templates/snippet/mainjs.html
{% load static %}
<script src="{% static 'js/mobiJS/jquery.min.js' %}"></script>
<script src="{% static 'js/mobiJS/tether.min.js' %}"></script>
<script src="{% static 'js/mobiJS/bootstrap.min.js' %}"></script>
<script src="{% static 'js/mobiJS/SmoothScroll.js' %}"></script>
<script src="{% static 'js/mobiJS/jquery.viewportchecker' %}.js"></script>
<script src="{% static 'js/mobiJS/script.min.js' %}"></script>
<script src="{% static 'js/mobiJS/jquery.touchSwipe' %}.min.js"></script>
<script src="{% static 'js/mobiJS/jarallax.js' %}"></script>
<script src="{% static 'js/mobiJS/script.js' %}"></script>

IIRC/templates/snippet/mobicss.html
{%load static%}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic&amp;subset=latin">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700&subset=latin,cyrillic">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Alegreya+Sans:400,700&subset=latin,vietnamese,latin-ext">
<link rel="stylesheet" href="{% static 'css/mobiCSS/et-line-font-style.css' %}">
<link rel="stylesheet" href="{% static 'css/mobiCSS/material.css' %}">
<link rel="stylesheet" href="{% static 'css/mobiCSS/tether.min.css' %}">
<!--<link rel="stylesheet" href="{% static 'css/mobiCSS/bootstrap.min.css' %}">-->
<link rel="stylesheet" href="{% static 'css/mobiCSS/awesomefont.css' %}">
<link rel="stylesheet" href="{% static 'css/mobiCSS/puritymstyle.css' %}">
<link rel="stylesheet" href="{% static 'css/mobiCSS/socicon.min.css' %}">
<!--<link rel="stylesheet" href="{% static 'css/mobiCSS/mobi-gallery.css' %}">-->
<!--<link rel="stylesheet" href="{% static 'css/mobiCSS/mobi-slider.css' %}">-->
<link rel="stylesheet" href="{% static 'css/mobiCSS/animate.min.css' %}">
<link rel="stylesheet" href="{% static 'css/mobiCSS/dropdownstyle.css' %}">
<link rel="stylesheet" href="{% static 'css/mobiCSS/style.css' %}">

<link rel="stylesheet" href="{% static 'css/mobiCSS/mbr-additional.css' %}" type="text/css">

IIRC/templates/snippet/navbar1.html
{%load static%}

<section id="menu-0">

    <nav class="navbar navbar-dropdown bg-color transparent navbar-fixed-top">
        <div class="container">

            <div class="mbr-table">
                <div class="mbr-table-cell">

                    <div class="navbar-brand">
                        <a href="../" class="navbar-logo">
                            <img src="{% static 'img/544x180-300x99-387x128-67.png' %}" alt="IIRC"></a>
                        <a class="navbar-caption" href="../">Iqbal Information and Research Center</a>
                    </div>

                </div>
                <div class="mbr-table-cell">

                    <button class="navbar-toggler pull-xs-right hidden-md-up" type="button" data-toggle="collapse"
                            data-target="#exCollapsingNavbar">
                        <div class="hamburger-icon"></div>
                    </button>

                    <ul class="nav-dropdown collapse pull-xs-right nav navbar-nav navbar-toggleable-sm"
                        id="exCollapsingNavbar">
                        <li class="nav-item"><a class="nav-link link" href="/en/">Home</a></li>
                        <!--<li class="nav-item dropdown">-->
                            <!--<a class="nav-link link dropdown-toggle" data-toggle="dropdown-submenu" href="/blogs/"-->
                               <!--aria-expanded="false">News</a>-->
                            <!--<div class="dropdown-menu">-->
                                <!--<a class="dropdown-item" href="/">Mobile friendly</a>-->
                                <!--<a class="dropdown-item" href="/">Based on Bootstrap</a>-->
                                <!--<div class="dropdown">-->
                                    <!--<a class="dropdown-item dropdown-toggle" data-toggle="dropdown-submenu" href="/">Trendy-->
                                        <!--blocks</a>-->
                                    <!--<div class="dropdown-menu dropdown-submenu">-->

                                        <!--<a class="dropdown-item" href="/">Image/content slider</a>-->
                                        <!--<a class="dropdown-item" href="/">Contact forms</a>-->
                                        <!--<a class="dropdown-item" href="/">Image gallery</a>-->
                                        <!--<a class="dropdown-item" href="/">Mobile menu</a>-->
                                        <!--<a class="dropdown-item" href="/">Google maps</a>-->
                                        <!--<a class="dropdown-item" href="/">Social buttons</a>-->
                                        <!--<a class="dropdown-item" href="/">Google fonts</a>-->
                                        <!--<a class="dropdown-item" href="/">Video background</a>-->
                                    <!--</div>-->
                                <!--</div>-->
                                <!--<a class="dropdown-item" href="/">Host anywhere</a>-->
                            <!--</div>-->
                        <!--</li>-->
                        <li class="nav-item"><a class="nav-link link" href="/contact/"
                                                aria-expanded="false">Contact</a></li>
                        <li class="nav-item"><a class="nav-link link" href="/about/"
                                                aria-expanded="false">About-us</a></li>
                        <li class="nav-item"><a class="nav-link link" href="/admin/"
                                                aria-expanded="false">Admin</a></li>
                        <!--<li class="nav-item dropdown">-->
                            <!--<a class="nav-link link dropdown-toggle" data-toggle="dropdown-submenu" href="/media/"-->
                               <!--aria-expanded="false">Media</a>-->
                            <!--<div class="dropdown-menu">-->
                                <!--<a class="dropdown-item" href="/image/">Images</a>-->
                                <!--<a class="dropdown-item" href="/video/">Videos</a>-->
                            <!--</div>-->
                        <!--</li>-->
                        <li class="nav-item"><input class="btn btn-primary" type = "button" id = "driver" value = "العربية" /></li>
                    </ul>
                    <button hidden="" class="navbar-toggler navbar-close" type="button" data-toggle="collapse"
                            data-target="#exCollapsingNavbar">
                        <div class="close-icon"></div>
                    </button>

                </div>
            </div>

        </div>
    </nav>


</section>

IIRC/templates/snippet/navbar2.html
{%load static%}
{% load pinax_blog_tags %}

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">
        <img src="{% static 'img/544x180-300x99-387x128-67.png' %}" width="80" height="35" alt="IIRC">
      </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/en/">Home <span class="sr-only">(current)</span></a>
      </li>
            </li>
            {% blog_sections as sections %}
            {% for section in sections %}
            {% if scoper_lookup %}
            {% url "pinax_blog:blog_section" scoper_lookup section.slug as section_url %}
            {% else %}
            {% url "pinax_blog:blog_section" section.slug as section_url %}
            {% endif %}
            <li class="nav-item">
                <a style="text-transform: capitalize;" class="nav-link" href="{{ section_url }}">{{ section.name }}</a>
            </li>
            {% endfor %}
        </ul>
        <form action="/ar/" class="form-inline mt-2 mt-md-0">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">العربية</button>
        </form>
    </div>
</nav>

IIRC/templates/snippet/navbar2withsearch.html
{%load static%}
{% load pinax_blog_tags %}

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">
        <img src="{% static 'img/544x180-300x99-387x128-67.png' %}" width="80" height="35" alt="IIRC">
      </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/en/">Home <span class="sr-only">(current)</span></a>
      </li>
            </li>
            {% blog_sections as sections %}
            {% for section in sections %}
            {% if scoper_lookup %}
            {% url "pinax_blog:blog_section" scoper_lookup section.slug as section_url %}
            {% else %}
            {% url "pinax_blog:blog_section" section.slug as section_url %}
            {% endif %}
            <li class="nav-item">
                <a style="text-transform: capitalize;" class="nav-link" href="{{ section_url }}">{{ section.name }}</a>
            </li>
            {% endfor %}
            <li class="nav-item">
                <a class="nav-link" href="#">Disabled</a>
            </li>
        </ul>
        {% if current_section == "all" %}
        {% if scoper_lookup %}
        {% url "pinax_blog:blog" scoper_lookup as search_url %}
        {% else %}
        {% url "pinax_blog:blog" as search_url %}
        {% endif %}
        {% else %}
        {% if scoper_lookup %}
        {% url "pinax_blog:blog_section" scoper_lookup current_section.slug as search_url %}
        {% else %}
        {% url "pinax_blog:blog_section" current_section.slug as search_url %}
        {% endif %}
        {% endif %}
        <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" aria-label="Search" type="search" placeholder="Search..." name="q"
                   value="{{ search_term|default:"" }}">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>